server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default
  flyway:
    enabled: false
  datasource:
    url: "jdbc:postgresql://${NAIS_DATABASE_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_DB_HOST}:${NAIS_DATABASE_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_DB_PORT}/${NAIS_DATABASE_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_DB_DATABASE}"
    username: ${NAIS_DATABASE_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_DB_USERNAME}
    password: ${NAIS_DATABASE_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_FLEX_REISETILSKUDD_BRUKERNOTIFIKASJON_DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        endpoint.identification.algorithm:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "flex-reisetilskudd-brukernotifikasjon"
      max-poll-records: 1
      auto-offset-reset: earliest #TODO sett til none når offsett er etablert i prod
      enable-auto-commit: false

logging.config: "classpath:logback.xml"

