DROP TABLE TIL_INNSENDING;
DROP TABLE TIL_UTFYLLING;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE TIL_UTFYLLING
(
    ID               VARCHAR(36) DEFAULT uuid_generate_v4() PRIMARY KEY,
    REISETILSKUDD_ID VARCHAR(36) UNIQUE,
    NOKKEL           VARCHAR(36),
    GRUPPERINGSID    VARCHAR(36),
    FNR              VARCHAR(11)              NOT NULL,
    EKSTERNT_VARSEL  BOOLEAN,
    SYNLIG_FREM_TIL  TIMESTAMP WITH TIME ZONE NOT NULL,
    BESKJED_SENDT    TIMESTAMP WITH TIME ZONE NOT NULL,
    DONE_SENDT       TIMESTAMP WITH TIME ZONE
);

CREATE TABLE TIL_INNSENDING
(
    ID               VARCHAR(36) DEFAULT uuid_generate_v4() PRIMARY KEY,
    REISETILSKUDD_ID VARCHAR(36) UNIQUE,
    NOKKEL           VARCHAR(36),
    GRUPPERINGSID    VARCHAR(36),
    FNR              VARCHAR(11)              NOT NULL,
    EKSTERNT_VARSEL  BOOLEAN,
    OPPGAVE_SENDT    TIMESTAMP WITH TIME ZONE NOT NULL,
    DONE_SENDT       TIMESTAMP WITH TIME ZONE
);

